development:
  adapter: postgresql
  encoding: utf8
  database: concert_app_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: concert_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: concert_app_production 
  pool: 5
